# Basic
title: Yanjie Li
subtitle: GET BUSY LIVING, OR GET BUSY DYING
welcome_message: <a href="#" target="_blank"></a>
creator: <a href="http://onev.cat">@onevcat</a>

url: "https://leeyegy.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: purple

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: About me, description: About me, url: 'https://leeyegy.github.io/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: leeyegy
    github: leeyegy
    twitter: leeyegy
    gplus: 107108267983477358170
    mail: leeyegy@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
